### ISSUE TITLE
Better error handling in programming examples

### ISSUE THREAD

**Issue by jburse** [jburse/jekejeke-samples#2]
We started displaying a better error dialog in case the knowledge
base initialization fails, by displaying the same error message as
for errors during the query execution:

```
    /**
     * <p>do set up of the knowledge base.</p>
     */
    private void initKnowledgebase() {
        try {
            Data.getKnowledgebase();
        } catch (Exception x) {
            /* simple problem exception handling */
            StringWriter sr = new StringWriter();
            x.printStackTrace(new PrintWriter(sr));
            JTextArea textarea = new JTextArea(sr.toString(), 8, 40);
            textarea.setLineWrap(true);
            JOptionPane.showMessageDialog(this,
                    new JScrollPane(textarea),
                    "Problem Report", JOptionPane.ERROR_MESSAGE);
       
         }
    }
```
The above is not optimal, since init knowledge base is a background
job, and it would be better if the background job would communicate
an error to the GUI thread, and from there the error would be shown.

This error back and forth is also part of this defect. Further the error
approach should be applied to other examples, such as:

- **Standalone frame:** We should also better display errors during
   knowledge base initialization, and preferably pass errors from background
   job to GUI thread.

- **Android activity, Android TV activity:** We should also better display errors during
   knowledge base initialization, and preferably pass errors from background
   job to GUI thread.

**Comment by jburse** [comment]
Here is an example of poor error handling in our example application,
not only during initialization. Take the Client example, if the server is not 
reachable, the URL request will time out. This is seen on the console:
```
Exception in thread "Thread-3" java.lang.RuntimeException: jekpro.tools.call.InterpreterException: Error: existence_error(source_sink, 'http://localhost:8082/example04/service.jsp?firstname=&name=&agefrom=50&ageto=&salaryfrom=&salaryto=')
	at example04.Stub.listRows(Stub.java:218)
	at example04.Client$3.run(Client.java:120)
	at example02.Pane$1.run(Pane.java:227)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jekpro.tools.call.InterpreterException: Error: existence_error(source_sink, 'http://localhost:8082/example04/service.jsp?firstname=&name=&agefrom=50&ageto=&salaryfrom=&salaryto=')
```
But no error is shown in the Client itself, and also the progress bar
is not switched off, so that the Client remains irresponsive:

![image](https://user-images.githubusercontent.com/5411487/94128957-11109580-fe5b-11ea-9615-16d8702bdb5f.png)

**Comment by jburse** [comment]
We now use the interface Callable from java.util.concurrent.
This interface is able to throw an Exception. The exception is
directly displayed from the background scheduler in the GUI

thread. Also the background scheduler now only takes one
argument. GUI update can be initiated from the background
by the application via SwingUtilities.invokeLater.
