### ISSUE TITLE
Broaden CheerpJ applet

### ISSUE THREAD

**Issue by jburse** [jburse/jekejeke-samples#8]
We experiment again using Cheerpj. In this ticket it
is seen how loading of a .jar and automatic execution
of the main class can be scripted:

**Harden CheerpJ weblet #69**
[https://\github.com/jburse/jekejeke-devel/issues/69](https://github.com/jburse/jekejeke-devel/issues/69)

In contrast to the CheerpJ chrome applet plugin, this
opens up extending applets to browsers beyond
chrome, into browsers such as Seamonkey etc...

We should realize our "applet" example with corresponding
pseudo applets. Namely we could do the following:

- **Swing Frame:** We could base our applet examples on the
   Standalone (Applet Disconnected) and Clinet (Applet Connected)
   examples. Using a Swing Frame again.
- **Frame Bounds:** We should position the frame at (0,0), and
   use the same size as the CheerpJ display, so that the 
   frame occupies the full CheerpJ display.
- **Frame Decoration:** We should switch off the window
  bar, with window title and window closer. This would
  make the applet feeling complete.

**Comment by jburse** [comment]
There is some progress concerning the Swing frame as applet.
A new issue popped up. When we configure the knowledge base
for weblet, it will use the interactor swing.

But the interactor swing requires more configuration. I guess
we did it wrong so far:

```
java.lang.IllegalArgumentException: null source
 	at java.util.EventObject(Unknown Source)
 	at omonia.util.frame.EnvironmentEvent(Unknown Source)
 	at jekpro.util.about.EnvironmentEventEnlist(Unknown Source)
 	at jekpro.util.abortable.InteractorSwing$1.run(Unknown Source)
 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 	at java.awt.EventQueue$3.run(Unknown Source)
 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by jburse** [comment]
We have discontinued CheerpJ support, so this ticket is obsolete.
